# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='hoovertext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
