# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20160917_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyparticipation',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
