# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
